networks:
  proxy:
    external: true

version: "3.8"
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    networks:
      - proxy
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: test
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data --console-address ":9001"
